---
common_packages:
  - git
  - curl
  - wget
  - rsync
  - cmake
  - make
  - gcc-c++
  - libcurl-devel
  - clang
  - python3
  - firewalld
  - policycoreutils-python-utils
wifi_packages:
  - NetworkManager-wifi
  - iw
  - wireless-regdb
  - mt7xxx-firmware
